--Creación de usuario
CREATE USER Katya IDENTIFIED BY Katya;
GRANT CONNECT, RESOURCE TO Katya;

--Creación de tablas
CREATE TABLE Usuarios (
    id INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT pk_Usuarios PRIMARY KEY (id)
);
CREATE TABLE Eventos (
    id INT NOT NULL AUTO_INCREMENT,
    fecha DATE NOT NULL,
    titulo VARCHAR(100) NOT NULL,
    ubicacion VARCHAR(255) NOT NULL,
    descripcion TEXT NOT NULL,
    CONSTRAINT pk_Eventos PRIMARY KEY (id)
);
CREATE TABLE Galerias ( 
    id INT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(100) NOT NULL,
    id_evento INT NOT NULL,
    CONSTRAINT pk_Galerias PRIMARY KEY (id),
    CONSTRAINT fk_Galerias_Eventos FOREIGN KEY (id_evento) REFERENCES Eventos(id) ON DELETE CASCADE
);
CREATE TABLE ImagenesGalerias (
    id INT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(100) NOT NULL,
    ruta_imagen VARCHAR(255) NOT NULL,
    id_galeria INT NOT NULL,
    CONSTRAINT pk_Imagenes_Galerias PRIMARY KEY (id),
    CONSTRAINT fk_Imagenes_Galerias FOREIGN KEY (id_galeria) REFERENCES Galerias(id) ON DELETE CASCADE
);
CREATE TABLE Favoritos (
    id_usuario INT NOT NULL,
    id_evento INT NOT NULL,
    CONSTRAINT pk_Favoritos PRIMARY KEY (id_usuario, id_evento),
    CONSTRAINT fk_Favoritos_Usuarios FOREIGN KEY (id_usuario) REFERENCES Usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_Favoritos_Eventos FOREIGN KEY (id_evento) REFERENCES Eventos(id) ON DELETE CASCADE
);

-- Creación de consultas
SELECT TITULO, FECHA, UBICACION
FROM GALERIAS 
JOIN EVENTOS E ON ID_EVENTO = ID
WHERE FECHA < TO_DATE('2026-03-01', 'YYYY-MM-DD')
ORDER BY FECHA DESC;

SELECT TITULO, FECHA, UBICACION
FROM EVENTOS 
JOIN FAVORITOS F ON ID = ID_EVENTO
WHERE ID_USUARIO = 1
ORDER BY FECHA ASC;

SELECT TITULO, RUTA_IMAGEN
FROM IMAGENES_GALERIAS
WHERE ID_GALERIA = 2
ORDER BY TITULO ASC;

SELECT TITULO, FECHA, DESCRIPCION
FROM EVENTOS 
JOIN FAVORITOS F ON ID = ID_EVENTO
WHERE ID_USUARIO = 2
AND FECHA > TO_DATE('2026-02-28', 'YYYY-MM-DD')
ORDER BY FECHA ASC;