/* CREACIÓN DE USUARIO Y PERMISOS */
CREATE USER Katya IDENTIFIED BY Katya;
GRANT CONNECT, RESOURCE TO Katya;
 
/* CREACIÓN DE LAS TABLAS */

CREATE TABLE EVENTOS( 
    ID number(3),
	FECHA date NOT NULL,
	TITULO varchar2(100) NOT NULL,
	UBICACION varchar2(255) NOT NULL,
	DESCRIPCION varchar2(500) NOT NULL,
    CONSTRAINT pk_EVENTOS PRIMARY KEY (ID)
    );

CREATE TABLE GALERIAS( 
    ID number(3),
	TITULO varchar2(100) NOT NULL,
	ID_EVENTO number(3) NOT NULL,
    CONSTRAINT pk_GALERIAS PRIMARY KEY (ID),
    CONSTRAINT fk_GALERIAS FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID)
    );
 
CREATE TABLE IMAGENES_GALERIAS( 
    ID number(4),
	TITULO varchar2(100) NOT NULL,
	RUTA_IMAGEN varchar2(255) NOT NULL,
	ID_GALERIA number(3) NOT NULL,
    CONSTRAINT pk_IMAGENES_GALERIAS PRIMARY KEY (ID),
    CONSTRAINT fk_IMAGENES_GALERIAS FOREIGN KEY (ID_GALERIA) REFERENCES GALERIAS(ID)
    );
 
CREATE TABLE USUARIOS( 
    ID number(3),
	NOMBRE varchar2(50) NOT NULL,
	EMAIL varchar2(100) NOT NULL UNIQUE,
	PASSWORD varchar2(255) NOT NULL,
    CONSTRAINT pk_USUARIOS PRIMARY KEY (ID)
    );
 
CREATE TABLE FAVORITOS( 
    ID_USUARIO number(3) NOT NULL,
	ID_EVENTO number(3) NOT NULL,
	CONSTRAINT pk_FAVORITOS PRIMARY KEY (ID_USUARIO, ID_EVENTO),
    CONSTRAINT fk_FavoritosUser FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID),
    CONSTRAINT fk_FavoritosEvent FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID)
    );
 
/* INSERCIÓN DE DATOS */
 
/* 6 Eventos obligatorios (3 pasados y 3 próximos al 28/02/2026) */
INSERT INTO EVENTOS VALUES (1, '01/01/2026', 'CONCIERTO AÑO NUEVO', 'TEATRO JOVELLANOS', 'MUSICA CLASICA');
INSERT INTO EVENTOS VALUES (2, '12/01/2026', 'CINE DE INVIERNO', 'SALA 1', 'PROYECCION ESPECIAL');
INSERT INTO EVENTOS VALUES (3, '24/01/2026', 'EXPOSICION FOTOGRAFIA', 'CENTRO CULTURAL', 'ARTE MODERNO');
INSERT INTO EVENTOS VALUES (4, '05/06/2026', 'FESTIVAL ROCK', 'AUDITORIO', 'BANDAS LOCALES');
INSERT INTO EVENTOS VALUES (5, '15/06/2026', 'TEATRO CLASICO', 'PLAZA MAYOR', 'OBRA DE CALLE');
INSERT INTO EVENTOS VALUES (6, '25/06/2026', 'FERIA DEL LIBRO', 'PARQUE CENTRAL', 'ENCUENTRO AUTORES');
 
/* 3 Usuarios */
INSERT INTO USUARIOS VALUES (1, 'CARLA', 'CARLA@GMAIL.COM', 'CARLA123');
INSERT INTO USUARIOS VALUES (2, 'PEPE', 'PEPE@GMAIL.COM', 'PEPE456');
INSERT INTO USUARIOS VALUES (3, 'JUAN', 'JUAN@GMAIL.COM', 'JUAN789');
 
/* Galerías para los 3 eventos del historial */
INSERT INTO GALERIAS VALUES (10, 'GALERIA CONCIERTO', 1);
INSERT INTO GALERIAS VALUES (20, 'GALERIA CINE', 2);
INSERT INTO GALERIAS VALUES (30, 'GALERIA EXPO', 3);
 
/* 3 Imágenes por cada galería */
INSERT INTO IMAGENES_GALERIAS VALUES (101, 'FOTO 1', 'img1.jpg', 10);
INSERT INTO IMAGENES_GALERIAS VALUES (102, 'FOTO 2', 'img2.jpg', 10);
INSERT INTO IMAGENES_GALERIAS VALUES (103, 'FOTO 3', 'img3.jpg', 10);
INSERT INTO IMAGENES_GALERIAS VALUES (201, 'CINE 1', 'cine1.jpg', 20);
INSERT INTO IMAGENES_GALERIAS VALUES (202, 'CINE 2', 'cine2.jpg', 20);
INSERT INTO IMAGENES_GALERIAS VALUES (203, 'CINE 3', 'cine3.jpg', 20);
INSERT INTO IMAGENES_GALERIAS VALUES (301, 'ARTE 1', 'arte1.jpg', 30);
INSERT INTO IMAGENES_GALERIAS VALUES (302, 'ARTE 2', 'arte2.jpg', 30);
INSERT INTO IMAGENES_GALERIAS VALUES (303, 'ARTE 3', 'arte3.jpg', 30);
 
/* Favoritos (3 por usuario, al menos 2 del historial) */
INSERT INTO FAVORITOS VALUES (1, 1);
INSERT INTO FAVORITOS VALUES (1, 2);
INSERT INTO FAVORITOS VALUES (1, 4);
INSERT INTO FAVORITOS VALUES (2, 2);
INSERT INTO FAVORITOS VALUES (2, 3);
INSERT INTO FAVORITOS VALUES (2, 5);
INSERT INTO FAVORITOS VALUES (3, 1);
INSERT INTO FAVORITOS VALUES (3, 3);
INSERT INTO FAVORITOS VALUES (3, 6);
 
COMMIT;
 
/* CONSULTAS */
 
/* A. Galerías anteriores al 28-02-2026 */
select GALERIAS.TITULO
from GALERIAS, EVENTOS
where (GALERIAS.ID_EVENTO = EVENTOS.ID) and (EVENTOS.FECHA < '28/02/2026');
 
/* B. Eventos favoritos del usuario 1 */
select EVENTOS.TITULO, EVENTOS.FECHA, EVENTOS.UBICACION
from EVENTOS, FAVORITOS
where (EVENTOS.ID = FAVORITOS.ID_EVENTO) and (FAVORITOS.ID_USUARIO = 1);
 
/* C. Imágenes de la galería del evento 12/01/2026 (ID 2) */
select IMAGENES_GALERIAS.TITULO, IMAGENES_GALERIAS.RUTA_IMAGEN
from IMAGENES_GALERIAS, GALERIAS
where (IMAGENES_GALERIAS.ID_GALERIA = GALERIAS.ID) and (GALERIAS.ID_EVENTO = 2);
 
/* D. Favoritos del usuario 2 posteriores al 28-02-2026 */
select EVENTOS.TITULO, EVENTOS.FECHA
from EVENTOS, FAVORITOS
where (EVENTOS.ID = FAVORITOS.ID_EVENTO) and (FAVORITOS.ID_USUARIO = 2) and (EVENTOS.FECHA > '28/02/2026');