/* CREACION DE USUARIO Y PERMISOS */
CREATE USER Katya IDENTIFIED BY Katya;
GRANT CONNECT, RESOURCE TO Katya;

/* CREACION DE LAS TABLAS */
CREATE TABLE USUARIOS( 
    ID number(10),
    NOMBRE varchar2(100) NOT NULL,
    EMAIL varchar2(100) NOT NULL UNIQUE,
    PASSWORD varchar2(255) NOT NULL,
    CONSTRAINT pk_USUARIOS PRIMARY KEY (ID)
);

CREATE TABLE EVENTOS( 
    ID number(10),
    FECHA date NOT NULL,
    TITULO varchar2(200) NOT NULL,   
    UBICACION varchar2(255) NOT NULL,
    DESCRIPCION varchar2(1000) NOT NULL, 
    CONSTRAINT pk_EVENTOS PRIMARY KEY (ID)
);

CREATE TABLE GALERIAS( 
    ID number(10),
    TITULO varchar2(200) NOT NULL,
    ID_EVENTO number(10) NOT NULL,
    CONSTRAINT pk_GALERIAS PRIMARY KEY (ID),
    CONSTRAINT fk_GALERIAS FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID) ON DELETE CASCADE
);

CREATE TABLE IMAGENES_GALERIAS( 
    ID number(10),
    TITULO varchar2(200) NOT NULL,
    RUTA_IMAGEN varchar2(500) NOT NULL, 
    ID_GALERIA number(10) NOT NULL,
    CONSTRAINT pk_IMAGENES_GALERIAS PRIMARY KEY (ID),
    CONSTRAINT fk_IMAGENES_GALERIAS FOREIGN KEY (ID_GALERIA) REFERENCES GALERIAS(ID) ON DELETE CASCADE
);

CREATE TABLE FAVORITOS( 
    ID_USUARIO number(10) NOT NULL,
    ID_EVENTO number(10) NOT NULL,
    CONSTRAINT pk_FAVORITOS PRIMARY KEY (ID_USUARIO, ID_EVENTO),
    CONSTRAINT fk_FAV_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID) ON DELETE CASCADE,
    CONSTRAINT fk_FAV_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID) ON DELETE CASCADE
);

COMMIT;
/* VISTAS */

/* A. Galerias anteriores al 28-02-2026 */
CREATE OR REPLACE VIEW VISTA_GALERIAS_ANTERIORES AS
SELECT GALERIAS.TITULO
FROM GALERIAS, EVENTOS
WHERE (GALERIAS.ID_EVENTO = EVENTOS.ID) 
AND (EVENTOS.FECHA < TO_DATE('28/02/2026', 'DD/MM/YYYY'));

/* B. Eventos favoritos del usuario 1 */
CREATE OR REPLACE VIEW VISTA_FAVORITOS_USUARIO1 AS
SELECT EVENTOS.TITULO, EVENTOS.FECHA, EVENTOS.UBICACION
FROM EVENTOS, FAVORITOS
WHERE (EVENTOS.ID = FAVORITOS.ID_EVENTO) 
AND (FAVORITOS.ID_USUARIO = 1);

/* C. Imagenes de la galeria del evento con ID 2 */
CREATE OR REPLACE VIEW VISTA_IMAGENES_EVENTO2 AS
SELECT IMAGENES_GALERIAS.TITULO, IMAGENES_GALERIAS.RUTA_IMAGEN
FROM IMAGENES_GALERIAS, GALERIAS
WHERE (IMAGENES_GALERIAS.ID_GALERIA = GALERIAS.ID) 
AND (GALERIAS.ID_EVENTO = 2);

/* D. Favoritos del usuario 2 posteriores al 28-02-2026 */
CREATE OR REPLACE VIEW VISTA_FAVORITOS_USUARIO2_PROXIMOS AS
SELECT EVENTOS.TITULO, EVENTOS.FECHA
FROM EVENTOS, FAVORITOS
WHERE (EVENTOS.ID = FAVORITOS.ID_EVENTO) 
AND (FAVORITOS.ID_USUARIO = 2) 
AND (EVENTOS.FECHA > TO_DATE('28/02/2026', 'DD/MM/YYYY'));